name: Todoist Readme

on:
  # workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: "0 0,9,12,15,18,21 * * *"

jobs:
  update-readme:
    name: Update todoist stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: abhisheknaiidu/todoist-readme@master
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          PREMIUM: ""
